server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/organicfood
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      connect-timeout: 2000ms
      timeout: 2000ms
      lettuce:
        pool:
          enabled: true
          max-active: 16
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
        shutdown-timeout: 100ms

app:
  cloudinary:
    cloud-name: dhwbwfip0
    api-key: 361748541597822
    api-secret: zzkJu931St1maw3CMbRHTGDcQoo
    folder: organicfood

  brevo:
    api-key: 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
    base-url: https://api.brevo.com/v3/
    sender-email: huynhmin1007@gmail.com
    sender-name: Organic Food